name: ncov daily report
on: 
  schedule:
    - cron: '12 0 */1 */1 */1'
  workflow_dispatch:

jobs:
  daily-report:
    runs-on: ubuntu-latest
    steps:

    - name: '[Prepare] Check out repo'
      uses: actions/checkout@v2

    - name: '[Prepare] Install Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        architecture: 'x64'

    - name: '[Prepare] Install Python library'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade requests

    - name: '[Main] Commit report and Push to WeChat'
      env:
        username: ${{ secrets.USERNAME }}
        pswd: ${{ secrets.PSWD }}
        geo_info: ${{ secrets.GEO_INFO }}
        sckey: ${{ secrets.SCKEY }}
      run: |
        python submit.py

